Repository packit/ogr, pull requests merged in 2019-09, with the labels that each got.

#182 Support GitlabAuthenticationError
  ogr/services/mock/gitlab.py
  tests/integration/test_gitlab.py
Labels: mergeit

#183 Fix typing in factory
  ogr/factory.py
Labels: mergeit

#185 method get_latest_release
  ogr/services/gitlab.py
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Releases.test_get_latest_release.yaml
  tests/integration/test_gitlab.py
Labels: GitLab, feature, mergeit

#184 gitlab: project info methods
  ogr/services/gitlab.py
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_get_description.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_get_git_urls.yaml
  tests/integration/test_gitlab.py
Labels: GitLab, feature, mergeit

#186 method get_sha_from_tag
  ogr/exceptions.py
  ogr/services/github.py
  ogr/services/gitlab.py
  tests/integration/test_data/test_github_data_tests.integration.test_github.GenericCommands.test_get_sha_from_tag.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_get_sha_from_tag.yaml
  tests/integration/test_github.py
  tests/integration/test_gitlab.py
Labels: mergeit

#187 tests on new repo
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_branches.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_email.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_get_description.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_get_file.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_get_git_urls.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_get_sha_from_tag.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_nonexisting_file.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_username.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Issues.test_close_issue.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Issues.test_create_issue.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Issues.test_get_all_issue_comments.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Issues.test_get_issue_list.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Issues.test_issue_info.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.PullRequests.test_get_all_pr_comments.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.PullRequests.test_get_all_pr_commits.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.PullRequests.test_pr_info.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.PullRequests.test_pr_list.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.PullRequests.test_update_pr_info.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Releases.test_create_release.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Releases.test_get_latest_release.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Releases.test_get_releases.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Tags.test_get_tags.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Tags.test_tag_from_tag_name.yaml
  tests/integration/test_gitlab.py
Labels: mergeit

#208 github method for creating projects added
  ogr/services/github.py
  tests/integration/test_data/test_github_data_tests.integration.test_github.Service.test_project_create.yaml
  tests/integration/test_data/test_github_data_tests.integration.test_github.Service.test_project_create_in_the_group.yaml
  tests/integration/test_github.py
Labels: mergeit

#206 methods for commit status and commit comment
  ogr/services/gitlab.py
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_commit_comment.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_get_commit_statuses.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_set_commit_status.yaml
  tests/integration/test_gitlab.py
Labels: mergeit

#210 Add trim parameter to set_commit_status method
  ogr/services/github.py
  tests/integration/test_data/test_github_data_tests.integration.test_github.GenericCommands.test_set_commit_status.yaml
  tests/integration/test_data/test_github_data_tests.integration.test_github.GenericCommands.test_set_commit_status_long_description.yaml
  tests/integration/test_github.py
Labels: mergeit

#217 Implement GitProject.get_web_url()
  ogr/abstract.py
  ogr/services/github.py
  ogr/services/gitlab.py
  ogr/services/pagure.py
  tests/integration/test_data/test_github_data_tests.integration.test_github.GenericCommands.test_get_web_url.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_get_web_url.yaml
  tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.GenericCommands.test_get_web_url.yaml
  tests/integration/test_github.py
  tests/integration/test_gitlab.py
  tests/integration/test_pagure.py
Labels: mergeit

#219 GitProject.full_repo_name
  ogr/abstract.py
  ogr/services/pagure.py
  tests/integration/test_data/test_github_data_tests.integration.test_github.GenericCommands.test_full_repo_name.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_full_repo_name.yaml
  tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.GenericCommands.test_full_repo_name.yaml
  tests/integration/test_github.py
  tests/integration/test_gitlab.py
  tests/integration/test_pagure.py
Labels: mergeit

#198 methods for pr and issue labels
  ogr/persistent_storage.py
  ogr/services/gitlab.py
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Issues.test_issue_labels.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.PullRequests.test_pr_labels.yaml
  tests/integration/test_gitlab.py
Labels: mergeit

#221 Remove pull requests from issues in GitHub implementation
  ogr/services/github.py
  tests/integration/test_data/test_github_data_tests.integration.test_github.GenericCommands.test_issue_permissions.yaml
  tests/integration/test_data/test_github_data_tests.integration.test_github.Issues.test_functions_fail_for_pr.yaml
  tests/integration/test_data/test_github_data_tests.integration.test_github.Issues.test_issue_list.yaml
  tests/integration/test_data/test_github_data_tests.integration.test_github.Issues.test_list_contains_only_issues.yaml
  tests/integration/test_github.py
Labels: GitHub, RHOSC, mergeit

#207 methods for permissions
  ogr/services/gitlab.py
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_get_owners.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_issue_permissions.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_pr_permissions.yaml
  tests/integration/test_gitlab.py
Labels: GitLab, mergeit

#227 Factor out getting collaborators (GithubProject)
  ogr/services/github.py
Labels: RHOSC, mergeit
