Repository packit/ogr, pull requests merged in 2019-10, with the labels that each got.

#226 Make PagureProject.full_repo_name property offline
  ogr/services/pagure.py
  tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.Comments.test_issue_comments.yaml
  tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.Comments.test_pr_comments.yaml
  tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.Comments.test_pr_comments_filter.yaml
  tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.Comments.test_pr_comments_reversed.yaml
  tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.Comments.test_pr_comments_search.yaml
  tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.GenericCommands.test_branches.yaml
  tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.GenericCommands.test_commit_statuses.yaml
  tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.GenericCommands.test_description.yaml
  tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.GenericCommands.test_full_repo_name.yaml
  tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.GenericCommands.test_get_file.yaml
  tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.GenericCommands.test_get_releases.yaml
  tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.GenericCommands.test_get_web_url.yaml
  tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.GenericCommands.test_git_urls.yaml
  tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.GenericCommands.test_issue_permissions.yaml
  tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.GenericCommands.test_pr_permissions.yaml
  tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.Issues.test_issue_info.yaml
  tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.Issues.test_issue_list.yaml
  tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.PullRequests.test_pr_info.yaml
  tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.PullRequests.test_pr_list.yaml
  tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.PullRequests.test_update_pr_info.yaml
  tests/integration/test_pagure.py
Labels: mergeit

#228 Implementation of get_issue_comments for projects
  ogr/services/github.py
  ogr/services/gitlab.py
  ogr/services/pagure.py
  tests/integration/test_data/test_github_data_tests.integration.test_github.Comments.test_issue_comments.yaml
  tests/integration/test_data/test_github_data_tests.integration.test_github.Comments.test_issue_comments_regex.yaml
  tests/integration/test_data/test_github_data_tests.integration.test_github.Comments.test_issue_comments_regex_reversed.yaml
  tests/integration/test_data/test_github_data_tests.integration.test_github.Comments.test_issue_comments_reversed.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Issues.test_get_issue_comments.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Issues.test_get_issue_comments_regex.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Issues.test_get_issue_comments_regex_reversed.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.Issues.test_get_issue_comments_reversed.yaml
  tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.Comments.test_issue_comments_regex.yaml
  tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.Comments.test_issue_comments_regex_reversed.yaml
  tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.Comments.test_issue_comments_reversed.yaml
  tests/integration/test_github.py
  tests/integration/test_gitlab.py
  tests/integration/test_pagure.py
Labels: RHOSC, feature, mergeit

#234 Update imports in Gitlab tests
  tests/integration/test_gitlab.py
Labels: mergeit

#235 Add Developer Certificate of Origin
  CONTRIBUTING.md
  DCO
Labels: mergeit

#239 prepare for rev dependency testing, set project dir in case it not come from zuul
  files/tasks/zuul-project-setup.yaml
Labels: mergeit

#241 Reverse dependency testing of packit
  .zuul.yaml
  files/tasks/checkout_packit.yaml
  files/zuul-reverse-dep-packit.yaml
Labels: mergeit

#242 Add project_create to PagureService and add tests for it
  ogr/exceptions.py
  ogr/services/pagure/service.py
  tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.Service.test_project_create.yaml
  tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.Service.test_project_create_in_the_group.yaml
  tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.Service.test_project_create_invalid_namespace.yaml
  tests/integration/test_pagure.py
Labels: RHOSC, mergeit

#246 Use new requre api
  tests/integration/__init__.py
  tests/replacements.py
Labels: mergeit

#257 improve typehints for parsing.py
  ogr/parsing.py
  ogr/services/github/project.py
  ogr/services/pagure/comments.py
Labels: mergeit

#256 Improve typehints for exceptions.py
  ogr/exceptions.py
Labels: mergeit
