Repository packit/ogr, pull requests merged in 2020-10, with the labels that each got.

#476 Unify project_create method
  ogr/abstract.py
  ogr/services/github/service.py
  ogr/services/gitlab/service.py
  tests/integration/github/test_data/test_service/tests.integration.github.test_service.Service.test_project_create_with_description.yaml
  tests/integration/github/test_service.py
  tests/integration/gitlab/test_data/test_service/tests.integration.gitlab.test_service.Service.test_project_create_with_description.yaml
  tests/integration/gitlab/test_service.py
  tests/integration/pagure/test_data/test_service/tests.integration.pagure.test_service.Service.test_project_create_with_description.yaml
  tests/integration/pagure/test_service.py
Labels: mergeit, 🌞 Friday 🤟

#477 Return `None` for user's email in Pagure
  ogr/services/pagure/user.py
Labels: mergeit, 🌞 Friday 🤟

#479 Implement project.exists for GitLab
  ogr/abstract.py
  ogr/services/gitlab/project.py
  ogr/services/pagure/project.py
  tests/integration/gitlab/test_data/test_generic_commands/tests.integration.gitlab.test_generic_commands.GenericCommands.test_project_exists.yaml
  tests/integration/gitlab/test_data/test_generic_commands/tests.integration.gitlab.test_generic_commands.GenericCommands.test_project_not_exists.yaml
  tests/integration/gitlab/test_generic_commands.py
Labels: GitLab, mergeit

#482 Remove files/tasks/zuul-project-setup.yaml
  files/tasks/zuul-project-setup.yaml
  files/zuul-install-requirements-rpms.yaml
  files/zuul-reverse-dep-packit.yaml
  files/zuul-tests.yaml
Labels: mergeit

#491 Update pre-commit configuration for prettier
  .pre-commit-config.yaml
Labels: mergeit

#489 Adding delete project functionality
  ogr/abstract.py
  ogr/services/github/project.py
  ogr/services/gitlab/project.py
  ogr/services/pagure/project.py
  tests/integration/github/test_data/test_generic_commands/tests.integration.github.test_generic_commands.GenericCommands.test_delete.yaml
  tests/integration/github/test_generic_commands.py
  tests/integration/gitlab/test_data/test_generic_commands/tests.integration.gitlab.test_generic_commands.GenericCommands.test_delete.yaml
  tests/integration/gitlab/test_generic_commands.py
  tests/integration/pagure/test_data/test_generic_commands/tests.integration.pagure.test_generic_commands.GenericCommands.test_delete.yaml
  tests/integration/pagure/test_generic_commands.py
Labels: mergeit

#488 Fix anonymous GitlabService
  ogr/services/gitlab/service.py
  tests/integration/gitlab/test_data/test_service/tests.integration.gitlab.test_service.Service.test_service_without_auth.yaml
  tests/integration/gitlab/test_service.py
Labels: mergeit
