Repository packit/ogr, pull requests merged in 2020-02, with the labels that each got.

#322 Pre-commit changes
  .packit.yaml
  .pre-commit-config.yaml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  files/packit-testing-farm-prepare.yaml
  files/tasks/build-rpm-deps.yaml
  files/tasks/generic-dnf-requirements.yaml
  files/tasks/install-ogr.yaml
  files/tasks/packit_reverse_dep_test.yaml
  files/tasks/python-compile-deps.yaml
  files/tasks/rpm-test-deps.yaml
  files/tasks/zuul-project-setup.yaml
  files/zuul-install-requirements-pip.yaml
  files/zuul-install-requirements-rpms.yaml
  files/zuul-reverse-dep-packit.yaml
  files/zuul-tests.yaml
  pre-commit-pb.yaml
  recipe.yaml
  setup.cfg
Labels: ready-for-review

#319 Remove trailing slash from URLs before parsing
  ogr/parsing.py
  tests/unit/test_parsing.py
Labels: mergeit

#320 Add `.gitignore` to repo
  .gitignore
Labels: mergeit

#321 Add support for tags when creating pagure issues.
  ogr/services/pagure/issue.py
  ogr/services/pagure/project.py
Labels: mergeit

#326 [CONTRIBUTING.md] update
  CONTRIBUTING.md
Labels: mergeit

#327 [.packit.yaml] remove no-longer needed keys & use aliases
  .packit.yaml
Labels: mergeit

#333 improve pagure error response
  ogr/services/pagure/service.py
Labels: ready-for-review, user-experience

#328 provide is_private method on GitProjects
  ogr/abstract.py
  ogr/services/github/project.py
  ogr/services/gitlab/project.py
  ogr/services/pagure/project.py
  tests/integration/test_data/test_github_data_tests.integration.test_github.GenericCommands.test_is_not_private.yaml
  tests/integration/test_data/test_github_data_tests.integration.test_github.GenericCommands.test_is_private.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_is_not_private.yaml
  tests/integration/test_data/test_gitlab_data_tests.integration.test_gitlab.GenericCommands.test_is_private.yaml
  tests/integration/test_data/test_pagure_data_tests.integration.test_pagure.PagureProjectTokenCommands.test_is_private.yaml
  tests/integration/test_github.py
  tests/integration/test_gitlab.py
  tests/integration/test_pagure.py
Labels: mergeit

#336 Do not use tokens and keys in the __str__ methods
  ogr/services/github/service.py
  ogr/services/gitlab/service.py
  ogr/services/pagure/service.py
Labels: mergeit

#335 diff url for pull-requests
  ogr/abstract.py
  ogr/read_only.py
  ogr/services/base.py
  ogr/services/github/pull_request.py
  ogr/services/gitlab/pull_request.py
  ogr/services/pagure/pull_request.py
  tests/integration/test_github.py
  tests/integration/test_gitlab.py
  tests/integration/test_pagure.py
Labels: mergeit, ready-for-review

#337 enable getting projects defined with SSH URLs
  ogr/factory.py
  tests/integration/test_data/test_factory/tests.integration.test_factory.FactoryTests.test_get_project_github.yaml
  tests/integration/test_factory.py
Labels: mergeit

#340 Allow to filter issues by labels.
  ogr/abstract.py
  ogr/services/github/issue.py
  ogr/services/github/project.py
  ogr/services/gitlab/issue.py
  ogr/services/gitlab/project.py
  ogr/services/pagure/issue.py
  ogr/services/pagure/project.py
  tests/integration/test_data/test_github/tests.integration.test_github.Issues.test_issue_list_labels.yaml
  tests/integration/test_data/test_gitlab/tests.integration.test_gitlab.Issues.test_issue_list_labels.yaml
  tests/integration/test_data/test_pagure/tests.integration.test_pagure.Issues.test_issue_list_labels.yaml
  tests/integration/test_github.py
  tests/integration/test_gitlab.py
  tests/integration/test_pagure.py
Labels: mergeit
