Repository packit/ogr, pull requests merged in 2020-04, with the labels that each got.

#361 Using pagination to retrieve pagure's full issue list
  ogr/services/pagure/issue.py
  tests/integration/test_data/test_pagure/tests.integration.test_pagure.Issues.test_issue_list_paginated.yaml
  tests/integration/test_pagure.py
Labels: mergeit

#375 print pagure API errors properly
  ogr/services/pagure/service.py
  tests/integration/test_data/test_pagure/tests.integration.test_pagure.PagureProjectTokenCommands.test_token_is_none_then_set.yaml
  tests/integration/test_pagure.py
Labels: mergeit, ready-for-review

#374 Add datetime to commitflags
  ogr/abstract.py
  ogr/services/github/flag.py
  ogr/services/gitlab/flag.py
  ogr/services/pagure/flag.py
  tests/integration/test_github.py
  tests/integration/test_gitlab.py
  tests/integration/test_pagure.py
Labels: mergeit

#378 use rpmautospec
  .gitignore
  .packit.yaml
  fedora/changelog
  fedora/python-ogr.spec
  files/tasks/build-rpm-deps.yaml
  files/tasks/generic-dnf-requirements.yaml
Labels: mergeit

#379 added CentOS prod/stg instances to pagure service
  ogr/services/pagure/service.py
Labels: ready-for-review

#382 packit.xml: set upstream_package_name
  .packit.yaml
Labels: mergeit

#380 Remove test jobs from zuul gating jobs
  .zuul.yaml
Labels: mergeit

#381 Set PR flags in Pagure
  ogr/services/pagure/pull_request.py
  tests/integration/test_data/test_pagure/tests.integration.test_pagure.PullRequests.test_set_pr_flag.yaml
  tests/integration/test_pagure.py
Labels: mergeit

#388 spec: dont hardcode name/version, use macros instead
  fedora/python-ogr.spec
Labels: mergeit

#390 revert rpmautospec
  fedora/changelog
  fedora/python-ogr.spec
Labels: mergeit

#389 Implement Issue setters for Pagure
  ogr/services/pagure/issue.py
  tests/integration/test_data/test_pagure/tests.integration.test_pagure.PagureProjectTokenCommands.test_issue_update_description.yaml
  tests/integration/test_data/test_pagure/tests.integration.test_pagure.PagureProjectTokenCommands.test_issue_update_title.yaml
  tests/integration/test_pagure.py
Labels: mergeit

#392 GitLab pagination
  ogr/services/gitlab/flag.py
  ogr/services/gitlab/project.py
  tests/integration/test_data/test_gitlab/tests.integration.test_gitlab.GenericCommands.test_branches_pagination.yaml
  tests/integration/test_data/test_gitlab/tests.integration.test_gitlab.Releases.test_get_releases_pagination.yaml
  tests/integration/test_gitlab.py
Labels: mergeit

#394 Zuul related refactoring changes
  .pre-commit-config.yaml
  .zuul.yaml
  files/tasks/install-ansible.yaml
  files/tasks/packit-requirements.yaml
  files/zuul-install-requirements-pip.yaml
  files/zuul-install-requirements-rpms.yaml
  files/zuul-pre-commit.yaml
  files/zuul-reverse-dep-packit.yaml
Labels: mergeit

#395 Add is_fork and username to PagureProject __str__
  ogr/services/pagure/project.py
  tests/integration/test_data/test_pagure/tests.integration.test_pagure.Forks.test_fork_in_str.yaml
  tests/integration/test_pagure.py
Labels: mergeit

#397 Switch backticks to apostrophes in Pagure errors
  ogr/services/pagure/service.py
Labels: mergeit

#399 spec: don't do python_provide on F33+
  fedora/python-ogr.spec
Labels: mergeit, ready-for-review

#402 Head commit on PRs
  ogr/services/github/pull_request.py
  ogr/services/gitlab/pull_request.py
  tests/integration/test_data/test_github/tests.integration.test_github.PullRequests.test_head_commit.yaml
  tests/integration/test_data/test_gitlab/tests.integration.test_gitlab.PullRequests.test_head_commit.yaml
  tests/integration/test_data/test_pagure/tests.integration.test_pagure.PullRequests.test_head_commit.yaml
  tests/integration/test_github.py
  tests/integration/test_gitlab.py
  tests/integration/test_pagure.py
Labels: mergeit

#403 Fix tests after requre update
  tests/integration/test_factory.py
Labels: mergeit

#401 Enhance project references in pull requests
  ogr/abstract.py
  ogr/services/base.py
  ogr/services/github/project.py
  ogr/services/github/pull_request.py
  ogr/services/github/service.py
  ogr/services/gitlab/pull_request.py
  ogr/services/gitlab/service.py
  ogr/services/pagure/pull_request.py
  tests/integration/test_data/test_github/tests.integration.test_github.PullRequests.test_source_project_fork_fork.yaml
  tests/integration/test_data/test_github/tests.integration.test_github.PullRequests.test_source_project_other_fork_fork.yaml
  tests/integration/test_data/test_github/tests.integration.test_github.PullRequests.test_source_project_renamed_fork.yaml
  tests/integration/test_data/test_github/tests.integration.test_github.PullRequests.test_source_project_renamed_upstream.yaml
  tests/integration/test_data/test_github/tests.integration.test_github.PullRequests.test_source_project_upstream_branch.yaml
  tests/integration/test_data/test_github/tests.integration.test_github.PullRequests.test_source_project_upstream_fork.yaml
  tests/integration/test_data/test_gitlab/tests.integration.test_gitlab.PullRequests.test_source_project_fork_fork.yaml
  tests/integration/test_data/test_gitlab/tests.integration.test_gitlab.PullRequests.test_source_project_other_fork_fork.yaml
  tests/integration/test_data/test_gitlab/tests.integration.test_gitlab.PullRequests.test_source_project_renamed_fork.yaml
  tests/integration/test_data/test_gitlab/tests.integration.test_gitlab.PullRequests.test_source_project_renamed_upstream.yaml
  tests/integration/test_data/test_gitlab/tests.integration.test_gitlab.PullRequests.test_source_project_upstream_branch.yaml
  tests/integration/test_data/test_gitlab/tests.integration.test_gitlab.PullRequests.test_source_project_upstream_fork.yaml
  tests/integration/test_data/test_pagure/tests.integration.test_pagure.PullRequests.test_source_project_upstream_branch.yaml
  tests/integration/test_data/test_pagure/tests.integration.test_pagure.PullRequests.test_source_project_upstream_fork.yaml
  tests/integration/test_github.py
  tests/integration/test_gitlab.py
  tests/integration/test_pagure.py
Labels: mergeit
